pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = 'Demo'
include('core')
project(':core').projectDir = file('../Seal-Engine-3M/core')
include('desktop')
project(':desktop').projectDir = file('../Seal-Engine-3M/desktop')
include 'game'
